apiVersion: apps/v1
kind: Deployment
metadata:
  name: catsdogs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catsdogs
  template:
    metadata:
      labels:
        app: catsdogs
    spec:
      containers:
      - name: api
        image: catsdogs-api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: catsdogs-service
spec:
  type: NodePort
  selector:
    app: catsdogs
  ports:
  - port: 8000
    targetPort: 8000